spring.datasource.url=jdbc:h2:mem:testdb
# config username and password
spring.datasource.username=sa
spring.datasource.password=

# path where h2 bank will start
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# set dialect to not throw error
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false